version: "3.9"
services:
  web:
    build: ./app
    restart: always
    ports:
    - 8080:8080
    environment:
      DB_HOST: db
      DB_PORT: 27017
      DB_USER: root
      DB_PASS: root
      FLASK_DEBUG: False
      FLASK_PORT: 8080
      FVWEB_SESSION_SECRET: S3CR37_CH4NG3_M3
      FVWEB_SESSION_LIFETIME: 15
  db:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
