version: "3.9"
services:
  web:
    build: ./app
    restart: unless-stopped
    ports:
    - 5000:5000
  db:
    image: mongo
    restart: unless-stopped
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 6nUwMUy1kM4fcrQp