version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    hostname: backend
    depends_on:
      - mongo
      - memcached
    links:
      - mongo
      - memcached
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_USER=fvweb
      - DB_PASSWORD=password
      - DB_NAME=fvweb
      - CACHE_HOST=memcached
      - CACHE_PORT=11211

  mongo:
    image: mongo
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fvweb
      - MONGO_INITDB_ROOT_PASSWORD=password

  memcached:
    image: memcached
    hostname: memcached
    ulimits:
      memlock: -1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    hostname: frontend
    depends_on:
      - backend
    links:
      - backend

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    links:
      - backend
      - frontend
