version: '3.9'
services:
  app:
    build: app
    deploy:
      replicas: 5
    ports:
      - 5000
    environment:
      - FLASK_SECRET=INSECURE_CHANGE_ME
      - FLASK_SESSION_LIFETIME=15
      - FLASK_PORT=5000
      - FLASK_DEBUG=true
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASS=NIvRqpZoWJ4vPEM5tjmA8gR0fmzj3pYDGB9T62AVjvDozMXIu1azjnC3bfLcnQUbq8cb0ePJZmThEUQFvqoBNqnZVJoY9LIW0MW
      - MONGO_SRV=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=tVBGaV1ASIZavCwOSKxqZPxIXgIR1QZ0yb1LglZGvVjQ2Q7nfsgFxbrstvYbJpUz1f1szhjpc6MIoqH5PObEhzfPCWOxscRyRyZ
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
  
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=NIvRqpZoWJ4vPEM5tjmA8gR0fmzj3pYDGB9T62AVjvDozMXIu1azjnC3bfLcnQUbq8cb0ePJZmThEUQFvqoBNqnZVJoY9LIW0MW
  
  redis:
    build: redis
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - app
